In [9]:
import pandas as pd
import numpy as np

In [ ]:
# creating series manually

In [13]:
s = pd.Series([10, 20, 30, 40], index = ['a', 'b', 'c', 'd'])
print("Series:\n", s)

Series:
 a    10
b    20
c    30
d    40
dtype: int64

In [17]:
prices = [649000, 391000, 5476000, 178600,1091000]
carnames = ['swift', 'santro', 'audi', 'elantra', 'bolero']

In [23]:
car_series = pd.Series(data = prices, index = carnames)
car_series

swift       649000
santro      391000
audi       5476000
elantra     178600
bolero     1091000
dtype: int64

In [25]:
car_series[car_series>1000000]

audi      5476000
bolero    1091000
dtype: int64

In [29]:

# write code to print the name of the customer who have sepent more than 300 rupees



cust_names = ['milan', 'pritesh', 'golu', 'ramit']
cust_bill = [156.78, 434.54, 109.25, 529.42]
cust_info = pd.Series(cust_bill, cust_names)

print(list(cust_info[cust_info>300].index))

['pritesh', 'ramit']

In [30]:
cust_info

milan      156.78
pritesh    434.54
golu       109.25
ramit      529.42
dtype: float64

In [31]:
cust_info[cust_info>300]

pritesh    434.54
ramit      529.42
dtype: float64

In [ ]:
# Handling DataFrames

In [34]:
df = pd.DataFrame({
    'Product': ['A', 'B', 'C'],
    'Price': [100, 150, 200],
    'Quantity': [5, 3,4]
})
print("\nDataFrame:\n", df)

DataFrame:
   Product  Price  Quantity
0       A    100         5
1       B    150         3
2       C    200         4

In [ ]:

# How to create csv file from existing dataframe data

In [35]:
import pandas as pd

In [41]:
df_csv = pd.DataFrame({
    'Product': ['Soap', 'Shampoo', 'Toothpaste', 'oil'],
    'Price': [100, 150, 200, 300],
    'Units_sold': [50, 30, 40, 50]
})
df_csv

      Product  Price  Units_sold
0        Soap    100          50
1     Shampoo    150          30
2  Toothpaste    200          40
3         oil    300          50

In [43]:
# save tocsv for use (in real scenario you would read from file)

df_csv.to_csv("retail_sales.csv", index=False)
print('file creating successfully')

file creating successfully

In [ ]:
# read csv using pandas

In [60]:
sales_data = pd.read_csv("retail_sales.csv")

print("\n csv data from 'retail_sales.csv':\n\n", sales_data)

 csv data from 'retail_sales.csv':

       Product  Price  Units_sold
0        Soap    100          50
1     Shampoo    150          30
2  Toothpaste    200          40
3         oil    300          50

In [61]:
sales_data[['Price','Units_sold']]

   Price  Units_sold
0    100          50
1    150          30
2    200          40
3    300          50

In [ ]:
# How to read csv file

In [65]:
# option 1

# import pandas as pd

# # load tha dataset
# file_path = "C:\\Users\\milan\\milan\\pharma_sales_data.csv"
# df = pd.read_csv(file_path)

In [63]:
df.head()

  Product  Price  Quantity
0       A    100         5
1       B    150         3
2       C    200         4

In [68]:
# # option 3
# file_path = "pharma_sales_data.csv"
# df = pd.read_csv(file_path)
# df.head()

In [ ]:
# panda 2

In [ ]:

# Example 1: loading data and finding missing values

In [2]:
# import pandas as pd

# # load dataset (replace with your path)
# df = pd.read_csv('data_clean.csv')
# df.head()

In [4]:
# print("missing values:\n", df.isnull().sum())

In [ ]:

# Example 2: imputation with mean/median/mode

In [9]:
df['Ozone']#before imputation

In [11]:
# fill 'ozane'with meadian (skewed data)
ozone_median = df['Ozone'].median()
print(ozone_median)

In [ ]:
df['Ozone'].fillna(ozone_median, inplace=True)

In [ ]:
df['Ozone']#after imputation

In [ ]:
df['Solar.R']#before imutation

In [ ]:
# fill 'solar.r' with mean (normalcdistribution)

solar_mean = df['Solar.R'].mean

In [ ]:


# case study: from data to diagnosis Handling missing values and Aggregating patient Records with pandas

In [5]:
import pandas as pd


df = pd.read_csv('encounter.csv')
print("First 5 rows of tha dataset")
df.head()

First 5 rows of tha dataset

,encounters.pat_id,encounters.pat_id_type,encounters.serv_date,encounters.ext_id,encounters.visit_type,encounters.location,encounters.discharge_date,encounters.chief_complaint,encounters.performing_user_id,encounters.performing_user_id_type,...,incidents.loc_description,incidents.status,incidents.date_last_worked,incidents.employee_starttime,incidents.reported_super_datetime,incidents.osha_work_related,incidents.osha_itype,incidents.workcomp_related,incidents.osha_completed_dt,incidents.privacy_case
0,10006,part:MIE,2014-01-08 08:30:00,10020,VISIT,OFFICE,2014-02-08 08:30:00,"Here for consultation for diabetes, hypertensi...",3213213218,id:npi,...,ABC Hospital,0,2014-01-08,22:53:00,2014-01-08 09:00:00,Yes,I,Yes,2014-01-08 10:00:00,0
1,111111111,id:ssn,2014-01-09 08:30:00,10021,VISIT,OFFICE,2014-02-09 08:30:00,"Here for consultation for diabetes, hypertensi...",3213213218,id:npi,...,ABC Hospital,0,2014-01-09,06:57:00,2014-01-09 09:00:00,Yes,I,Yes,2014-01-09 10:00:00,0
2,10006,part:MIE,2014-01-10 08:30:00,10022,VISIT,OFFICE,2014-02-10 08:30:00,"Here for consultation for diabetes, hypertensi...",3213213218,id:npi,...,ABC Hospital,2,2014-01-10,09:56:00,2014-01-10 09:00:00,Yes,I,Yes,2014-01-10 10:00:00,0
3,10019,part:MIE,2014-01-11 08:30:00,10023,VISIT,OFFICE,2014-02-11 08:30:00,"Here for consultation for diabetes, hypertensi...",3213213218,id:npi,...,ABC Hospital,2,2014-01-11,10:15:00,2014-01-11 09:00:00,Yes,I,Yes,2014-01-11 10:00:00,0
4,10006,part:MIE,2014-01-12 08:30:00,10024,VISIT,OFFICE,2014-02-12 08:30:00,"Here for consultation for diabetes, hypertensi...",3213213218,id:npi,...,ABC Hospital,2,2014-01-12,09:55:00,2014-01-12 09:00:00,Yes,I,Yes,2014-01-12 10:00:00,1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 28 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   encounters.pat_id                   8 non-null      int64
 1   encounters.pat_id_type              8 non-null      object
 2   encounters.serv_date                8 non-null      object
 3   encounters.ext_id                   8 non-null      int64
 4   encounters.visit_type               8 non-null      object
 5   encounters.location                 8 non-null      object
 6   encounters.discharge_date           8 non-null      object
 7   encounters.chief_complaint          8 non-null      object
 8   encounters.performing_user_id       8 non-null      int64
 9   encounters.performing_user_id_type  8 non-null      object
 10  encounters.closed                   8 non-null      int64
 11  incidents.inc_datetime              8 non-null      object
 12  incidents.case_type                 8 non-null      object
 13  incidents.loc_state                 8 non-null      object
 14  incidents.comment_activity          8 non-null      object
 15  incidents.comment_explanation       8 non-null      object
 16  incidents.comment_cause             8 non-null      object
 17  incidents.case_number               8 non-null      object
 18  incidents.loc_description           8 non-null      object
 19  incidents.status                    8 non-null      int64
 20  incidents.date_last_worked          8 non-null      object
 21  incidents.employee_starttime        8 non-null      object
 22  incidents.reported_super_datetime   8 non-null      object
 23  incidents.osha_work_related         8 non-null      object
 24  incidents.osha_itype                8 non-null      object
 25  incidents.workcomp_related          8 non-null      object
 26  incidents.osha_completed_dt         8 non-null      object
 27  incidents.privacy_case              8 non-null      int64
dtypes: int64(6), object(22)
memory usage: 1.9+ KB

In [ ]:
# 2. column selection & filtering select columns of interest

In [7]:
possible_cols = ['encounters.visit_type']

In [ ]:
# 3.Handling missing values

In [11]:
# print("\nmissing values in each column:")
# df.isnull.sum()

In [ ]:
# drop row where 'ReasonDescription' is missing

In [12]:
df.dropna(subset = ['encounters.pat_id_type'], inplace= True)
print("\nAfter handling missing values:")
df.head()

After handling missing values:

,encounters.pat_id,encounters.pat_id_type,encounters.serv_date,encounters.ext_id,encounters.visit_type,encounters.location,encounters.discharge_date,encounters.chief_complaint,encounters.performing_user_id,encounters.performing_user_id_type,...,incidents.loc_description,incidents.status,incidents.date_last_worked,incidents.employee_starttime,incidents.reported_super_datetime,incidents.osha_work_related,incidents.osha_itype,incidents.workcomp_related,incidents.osha_completed_dt,incidents.privacy_case
0,10006,part:MIE,2014-01-08 08:30:00,10020,VISIT,OFFICE,2014-02-08 08:30:00,"Here for consultation for diabetes, hypertensi...",3213213218,id:npi,...,ABC Hospital,0,2014-01-08,22:53:00,2014-01-08 09:00:00,Yes,I,Yes,2014-01-08 10:00:00,0
1,111111111,id:ssn,2014-01-09 08:30:00,10021,VISIT,OFFICE,2014-02-09 08:30:00,"Here for consultation for diabetes, hypertensi...",3213213218,id:npi,...,ABC Hospital,0,2014-01-09,06:57:00,2014-01-09 09:00:00,Yes,I,Yes,2014-01-09 10:00:00,0
2,10006,part:MIE,2014-01-10 08:30:00,10022,VISIT,OFFICE,2014-02-10 08:30:00,"Here for consultation for diabetes, hypertensi...",3213213218,id:npi,...,ABC Hospital,2,2014-01-10,09:56:00,2014-01-10 09:00:00,Yes,I,Yes,2014-01-10 10:00:00,0
3,10019,part:MIE,2014-01-11 08:30:00,10023,VISIT,OFFICE,2014-02-11 08:30:00,"Here for consultation for diabetes, hypertensi...",3213213218,id:npi,...,ABC Hospital,2,2014-01-11,10:15:00,2014-01-11 09:00:00,Yes,I,Yes,2014-01-11 10:00:00,0
4,10006,part:MIE,2014-01-12 08:30:00,10024,VISIT,OFFICE,2014-02-12 08:30:00,"Here for consultation for diabetes, hypertensi...",3213213218,id:npi,...,ABC Hospital,2,2014-01-12,09:55:00,2014-01-12 09:00:00,Yes,I,Yes,2014-01-12 10:00:00,1

In [ ]:
# average of column name baseencountercost for encounterclass column

In [14]:
# avg_cost_by_calss= df.groupby('encounters.chief_complaint') ['encounters.serv_date'].mean()
# print("\average complaint in encounter:")
# print(avg_cost_by_calss)

In [17]:
# sort encounter y highest base cst
sorted_df = df.sort_values(by= 'encounters.location', ascending=False)
print("\n top 4 most expensive encounter:")
sorted_df[['encounters.chief_complaint']].head()

 top 4 most expensive encounter:

                          encounters.chief_complaint
0  Here for consultation for diabetes, hypertensi...
1  Here for consultation for diabetes, hypertensi...
2  Here for consultation for diabetes, hypertensi...
3  Here for consultation for diabetes, hypertensi...
4  Here for consultation for diabetes, hypertensi...